// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shtgwugkbajtkvxgqens.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNodGd3dWdrYmFqdGt2eGdxZW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxNzI3MDAsImV4cCI6MjA3NTc0ODcwMH0.rlhLduGPfmPIwk4Ld7IElH17KL7kh29qz1d2q0rDuck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});